version: "3.2"

services:
  nginx_base:
    container_name: nginx_base
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_base

  php_base:
    container_name: php_base
    build:
      context: "./php/"
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/sf
